---
dist: trusty
services: docker
cache: cargo
language: rust
rust:
  - nightly
  - "1.39.0"
  - stable

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

install:
  - bash ci/install.sh

script:
  # Use included bindings
  - cross test --target armv7-unknown-linux-gnueabihf
  # Generate bindings from headers
  - cross test --target armv7-unknown-linux-gnueabihf --features generate_bindings
  # Fudge sanity checks and build docs
  - MMAL_INCLUDE_DIR=/tmp MMAL_LIB_DIR=/tmp cross doc --target armv7-unknown-linux-gnueabihf

deploy:
  # Upload the documentation from the build with stable
  # Runs on the master branch, not individual PRs
  provider: script
  script: bash ci/docs.sh
  skip_cleanup: true
  on:
    branch: master
    rust: stable
