[build.env]
passthrough = [
  "RUST_BACKTRACE",
  "RUST_LOG",
  "MMAL_LIB_DIR",
  "MMAL_INCLUDE_DIR"
]

# Raspberry Pi 3
[target.armv7-unknown-linux-gnueabihf]
image = "test-cross:armv7-unknown-linux-gnueabihf-0.1.16"
